// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLvBO_25FeRyy1hJ6SmYeujDFryOT72_U',
    appId: '1:827707173369:web:0eb668978bd4c216b03528',
    messagingSenderId: '827707173369',
    projectId: 'linerb',
    authDomain: 'linerb.firebaseapp.com',
    storageBucket: 'linerb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdAIuxWw6OiIDcGs8sGYXB67hrobzOO5M',
    appId: '1:827707173369:android:bc792438df6ea3b3b03528',
    messagingSenderId: '827707173369',
    projectId: 'linerb',
    storageBucket: 'linerb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0uNYDXwP0WDfhS6m30KaaInobLkRDROo',
    appId: '1:827707173369:ios:4a3a091b1905385cb03528',
    messagingSenderId: '827707173369',
    projectId: 'linerb',
    storageBucket: 'linerb.firebasestorage.app',
    iosBundleId: 'com.example.linerb',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0uNYDXwP0WDfhS6m30KaaInobLkRDROo',
    appId: '1:827707173369:ios:4a3a091b1905385cb03528',
    messagingSenderId: '827707173369',
    projectId: 'linerb',
    storageBucket: 'linerb.firebasestorage.app',
    iosBundleId: 'com.example.linerb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLvBO_25FeRyy1hJ6SmYeujDFryOT72_U',
    appId: '1:827707173369:web:596dc0b2dc6938fdb03528',
    messagingSenderId: '827707173369',
    projectId: 'linerb',
    authDomain: 'linerb.firebaseapp.com',
    storageBucket: 'linerb.firebasestorage.app',
  );
}
